# Generated by Django 5.0 on 2024-01-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='cons_ID',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='event',
            name='instructor',
        ),
        migrations.AlterField(
            model_name='venue',
            name='email_address',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='web',
            field=models.URLField(null=True, verbose_name='Website Address'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='zip_code',
            field=models.CharField(max_length=15, null=True, verbose_name='Zip Code'),
        ),
        migrations.AddField(
            model_name='event',
            name='instructor',
            field=models.ManyToManyField(blank=True, to='events.consultant'),
        ),
    ]
