# Generated by Django 5.0 on 2024-01-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_contact_event_status'),
    ]

    operations = [

        migrations.AddField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default='2024-01-01 00:00:00', verbose_name='end'),
        ),
        migrations.AddField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default='2024-01-01 00:00:00', verbose_name='start'),
        ),
    ]
