# Generated by Django 5.0 on 2024-01-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_event_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateTimeField(default='2024-01-01 00:00:00', verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateTimeField(default='2024-01-01 00:00:00', verbose_name='start'),
        ),
    ]
