# Generated by Django 5.0 on 2024-01-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_end_alter_event_start'),
    ]


