# Generated by Django 5.0 on 2024-01-12 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_event_event_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.consultant'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('softbooked', 'Soft Booked'), ('hardbooked', 'Hard Booked'), ('custom_on_hold', 'On Hold')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.venue'),
        ),
    ]
