# Generated by Django 5.0 on 2024-01-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_instructor_alter_event_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_number', models.CharField(max_length=25, verbose_name='Course Identifier')),
                ('course_title', models.CharField(max_length=200, verbose_name='Course Title')),
                ('number_of_days', models.IntegerField(verbose_name='Course Duration (Days)')),
                ('certification', models.CharField(max_length=100, verbose_name='Certification')),
            ],
        ),
    ]
