# Generated by Django 5.0 on 2024-01-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_rename_number_of_days_course_course_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date_from',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date_to',
        ),
    ]
