# Generated by Django 5.0 on 2024-01-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_remove_course_number_of_days_course_course_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification', models.CharField(max_length=25, null=True, verbose_name='Certification')),
                ('cert_title', models.CharField(max_length=250, null=True, verbose_name='Cert Title')),
                ('cert_type', models.CharField(max_length=45, null=True, verbose_name='Cert Title')),
            ],
        ),
    ]
