# Generated by Django 5.0 on 2024-01-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='cert_type',
        ),
        migrations.AddField(
            model_name='certificate',
            name='cert_attained',
            field=models.DateField(null=True, verbose_name='Cert Attained'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='cert_expires',
            field=models.DateField(null=True, verbose_name='Cert Expires'),
        ),
    ]
