# Generated by Django 5.0 on 2024-02-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_consultant_user_cons_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='user',
            field=models.IntegerField(default=1, verbose_name='user_id'),
            preserve_default=False,
        ),
    ]
