# Generated by Django 5.0 on 2024-02-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_alter_event_instructor_alter_cons_course_consultant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, max_length=25, null=True),
        ),
    ]
